version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=stage_medecine
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=djangostagemedecine#2021
  web:
    build: .
    command: sh -c "python stage_medecine/manage.py wait_for_database &&
             python stage_medecine/manage.py makemigrations &&
             python stage_medecine/manage.py migrate &&
             python stage_medecine/manage.py collectstatic --noinput &&
             python stage_medecine/manage.py create_superuser_with_password --username superadmin --password admin --noinput --email 'blank@email.com' --preserve &&
             python stage_medecine/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
