# Generated by Django 3.1.6 on 2021-02-17 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Promotion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectCode',
            fields=[
                ('unique_id', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_points', models.FloatField(default=0.0)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.connectcode')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.class')),
                ('stages_done', models.ManyToManyField(to='stages.StageDone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
