# Generated by Django 3.1.6 on 2021-02-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210220_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.class'),
        ),
    ]
