# Generated by Django 3.1.6 on 2021-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_category_mandatory'),
        ('users', '0004_auto_20210220_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stages_done',
            field=models.ManyToManyField(blank=True, null=True, to='stages.StageDone'),
        ),
    ]
