# Generated by Django 3.1.6 on 2021-02-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Period', max_length=100)),
                ('date_start', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stage', max_length=100)),
                ('place_min', models.IntegerField(default=0)),
                ('place_max', models.IntegerField(default=0)),
                ('guard', models.BooleanField(default=False)),
                ('town', models.CharField(default='Caen', max_length=100)),
                ('hospital', models.CharField(default='CHU', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stages.category')),
            ],
        ),
        migrations.CreateModel(
            name='StageDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.period')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage')),
            ],
        ),
    ]
