# Generated by Django 3.1.6 on 2021-02-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_category_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedone',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
