# Generated by Django 3.1.6 on 2021-02-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_auto_20210217_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='town',
        ),
    ]
