name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: djangostagemedecine#2021
          POSTGRES_DB: stage_medecine_db
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test
        run: |
          python app/manage.py migrate
          python app/manage.py test stage_medecine

      - name: Generate the documentation
        run: |
          python app/manage.py spectacular --file doc.yml

      - name: Generate the html of the documentation
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/doc.yml -g html2 -o /local

      - name: Archive HTML documentation
        uses: actions/upload-artifact@v2
        with:
          name: swagger-html
          path: index.html