# Generated by Django 3.1.6 on 2021-03-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
